services:
  api:
    container_name: core_svc
    build:
      context: ../../core
      dockerfile: ./Dockerfile
    env_file:
      - ../../core/.env
    ports:
      - "8080:8080"
    expose:
      - "9100"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    external: true
    name: gig-platform
